### ISSUE TITLE
Storm not installing

### ISSUE THREAD

**Issue by ctippur** [Lewuathe/storm-cookbook#18]
Hello,

I am trying to use this cookbook to install on a local vagrant server via chef-colo

I have edited storm-cluster-0.0.21/attributes/storm_yaml.rb and added localhost to these attributes.

default['storm']['storm_yaml']['nimbus.host'] = 'localhost'
default['storm']['storm_yaml']['storm.zookeeper.servers'] = ['localhost']

I dont see that storm is being installed. 

Appreciate any help.
- Shekar

**Comment by Lewuathe** [comment]
@ctippur Thank you for reporting issue. I'll release v0.0.22.
