### ISSUE TITLE
unconditionally includes apt recipe

### ISSUE THREAD

**Issue by petere** [Lewuathe/storm-cookbook#20]
As of release v0.0.22, this cookbook unconditionally runs the `apt` recipe, which is inappropriate for non-APT-based systems.

**Comment by Lewuathe** [comment]
@petere Thank you so much for reporting!

I removed `apt` cookbook from common recipe at #21. But current storm-cluster cookbook support only ubuntu platform. So do you mean we should support other platforms at this time?

**Comment by petere** [comment]
It works fine on CentOS, and the `.kitchen.yml` file even tests CentOS. So I had assumed that it was supported.

**Comment by Lewuathe** [comment]
@petere I'm sorry. That's mistake. storm-cookbook does not be tested on CentOS platform currently. 

But with #21 PR, we removed an `apt` recipe from common recipe. Although it requires us to write `run_list[apt]` in user cookbook, it may enables us to run our cookbook on CentOS. 
I want to try and test it. Thank you so much for a feedback!

**Comment by petere** [comment]
That works.

I tried to improve support for CentOS, but the upstart version in CentOS 6 is too old to support the provided upstart configuration.  So that won't be as easy, but keeping the `common` recipe working independent of platform will be useful, because that helps with the installation.
